name: "Build Image (Dockerhub)"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_call: {}

jobs:
  build-dockerhub-image:
    uses: sagansystems/gladly-github-actions/.github/workflows/build-dockerhub-image.yaml@v1
    with:
      dockerhub-repository: build-harness
      push: ${{ github.event_name != 'pull_request' }}
      use-ssh: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SSH_PRIVATE_KEY: |
        ${{ secrets.SAGANBOT_SSH_PRIVATE_KEY }}
