name: "Build Image (Dockerhub)"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_call: {}

jobs:
  build-dockerhub-image:
    uses: sagansystems/gladly-github-actions/.github/workflows/build-dockerhub-image.yaml@master
    with:
      dockerhub-repository: build-harness
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      inherit
